### ISSUE TITLE
Links with accentuated character

### ISSUE THREAD

**Issue by gilleschapron** [GooRoo/mkdocs-obsidian-bridge#10]
Thanks you for your fantastic work on this mkdocs plugin.

I'm using it to make my doc which is bilingual, english and french.

When I make a wikilink to a title in french that have some accentuated characters (é, à, apostrophe ' etc.), these characters are kept in the generated link, and then the link does not work.

I have also multiple warning because I'm using 
https://ultrabug.github.io/mkdocs-static-i18n/fr/getting-started/quick-start/
to simplify multiple language doc generation, and my files are stored in some subfolder "en" and "fr".

If you could add accentuated character conversion, it will be great (I'll will make a try myself).

Gilles

**Comment by GooRoo** [comment]
Hi @gilleschapron,
Thanks for the feedback.

This was done intentionally. I'm actually also using my plugin for bilingual docs (Ukrainian + English) and it somehow didn't work for me otherwise.

Good news is that AFAIR it's possible to override this behavior in the config. Bad news is that I don't remember how exactly. Let me check, pls.
